// Reef: the Qt face over blaketestnode's browser node. The worker is the node's own (pinned by commit), loaded through a
// blob so this stays one page; the page drives its phases (fetch, hash, verify, sync) and shows them the way a node does.
const $ = (id) => document.getElementById(id);
const NODE = 'https://cdn.jsdelivr.net/gh/bitcoin-blake/blaketestnode@c6cbed10adac743a9e6721dbf0c193d17ae68731';
const LIB = 'https://cdn.jsdelivr.net/gh/sidestr/spec@fe689e9c723f9bf43393d2dd5b6f924a701c8a18/siding/lib', CDN = 'https://cdn.jsdelivr.net/gh/bitcoin-desktop/schema@v0.0.27';
const DEFAULT_RELAYS = ['wss://nos.lol', 'wss://relay.primal.net', 'wss://nostr.mom', 'wss://nostr.oxtr.dev'];
const OPT_DEFAULTS = { unit: 'tbtc', feeRate: 1, notify: true, mask: false, relays: DEFAULT_RELAYS, torrent: false, seed: false };
const OPT = (() => { try { return { ...OPT_DEFAULTS, ...JSON.parse(localStorage.getItem('reef:options') ?? '{}') }; } catch { return { ...OPT_DEFAULTS }; } })();
const saveOptions = () => { try { localStorage.setItem('reef:options', JSON.stringify(OPT)); } catch {} };
const RELAYS = () => (OPT.relays?.length ? OPT.relays : DEFAULT_RELAYS);
const q = new URLSearchParams(location.search); const LS = { get: (k) => { try { return localStorage.getItem(k); } catch { return null; } }, set: (k, v) => { try { localStorage.setItem(k, v); } catch {} } };
const SNAP_URL = q.get('snapshot') ?? LS.get('reef:snapshot') ?? 'https://melvin.me/public/txbt4/utxo-knots-150307.dat';
const BLOCKS_URL = q.get('blocks') ?? LS.get('reef:blocks') ?? 'https://melvin.me/public/txbt4/txbt4-blocks';
LS.set('reef:snapshot', SNAP_URL); LS.set('reef:blocks', BLOCKS_URL);
const fmt = (t) => t ? new Date(t * 1000).toLocaleString(undefined, { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) : '…';
const { createTabNode, mib, secs, n, eta } = await import(`${NODE}/browser/tabnode.js`);
const T0 = Date.now(); $('startup').textContent = fmt(Math.floor(T0 / 1000)); $('i-snapurl').textContent = SNAP_URL; $('i-blocks').textContent = `${BLOCKS_URL}.dat, mirrored into OPFS`;
// ---- node state, filled by the worker's messages
const tn = createTabNode({ base: NODE, snapshotUrl: SNAP_URL, blocksUrl: BLOCKS_URL, torrent: OPT.torrent, seed: OPT.seed }); const node = tn.node; const post = (m) => tn.post(m); const seedStart = () => tn.seedStart(); const seedStop = () => tn.seedStop();
function setSync(msg, pct, eta) { $('syncmsg').textContent = msg; if (pct == null) { $('pb').hidden = true; $('synceta').textContent = ''; } else { $('pb').hidden = false; $('pbi').style.width = Math.max(0, Math.min(100, pct)).toFixed(1) + '%'; $('synceta').textContent = `${pct.toFixed(0)}%${eta ? ' · ' + eta : ''}`; } }
function renderHist() { $('i-hist').innerHTML = node.hist.map(([k, v]) => `<span class="l">${k}</span><span class="v">${secs(v)}</span>`).join('') + `<span class="l" style="font-weight:600">total</span><span class="v">${secs(node.hist.reduce((a, [, v]) => a + v, 0))}</span>`; }
function renderInfo() { const st = node.st; if (st) { $('i-datadir').textContent = `origin private file system (OPFS), ${st.usage ? mib(st.usage) + ' used' : 'usage unknown'}${st.quota ? ' of ' + (st.quota / 1073741824).toFixed(1) + ' GiB' : ''}`; $('i-snapdisk').textContent = st.dat < 0 ? 'absent' : st.dat >= st.expect.bytes ? `complete, ${mib(st.dat)}` : `${mib(st.dat)} of ${mib(st.expect.bytes)}${st.partial ? ' (resumable)' : ''}`; $('i-sha').textContent = st.sha ? (st.sha === st.expect.sha256 ? st.sha + ' — matches the pinned value' : 'MISMATCH ' + st.sha) : 'not checked yet'; if (st.idx > 0 && !node.hs) $('i-hs').textContent = `${st.expect.txoutsetHash} — verified on an earlier visit; index ${mib(st.idx)}`; if (!node.coins) $('i-coins').textContent = `${n(st.expect.coins)} expected`; }
  if (node.hs) $('i-hs').textContent = `${node.hs} — recomputed from the file, ${node.hsOk ? 'matches' : 'MISMATCH'}`; if (node.coins) $('i-coins').textContent = `${n(node.coins)} in ${n(node.txids)} txids`;
  $('i-height').textContent = node.height != null ? n(node.height) : '…'; $('lbt').textContent = fmt(node.time); $('i-hash').innerHTML = node.hash ? `<a href="https://mempool.guide/testnet4/block/${node.hash}" target="_blank" rel="noopener" style="color:inherit">${node.hash}</a>` : '…'; $('i-mem').textContent = performance.memory ? `${Math.round(performance.memory.usedJSHeapSize / 1048576)} MB heap (page)` : 'not exposed by this browser';
  if (node.nostr) $('i-nostr').textContent = `${n(node.nostr.height)} · ${node.nostr.hash.slice(0, 16)}… · ${node.nostr.relay} · ${node.nostr.agree} tail hashes agree with the file${node.nostr.live ? ' · live' : ''}`;
  $('tr-recv').textContent = `${(node.recv / 1e6).toFixed(2)} MB`; $('tr-sent').textContent = `${(node.sent / 1e6).toFixed(2)} MB`; $('conn').setAttribute('title', `1 mirror (${BLOCKS_URL}) and the relays the tip announcement comes from`); }
window.reef = { node, tn, OPT }; // for a look from the devtools console
function onMessage(m) {
  if (m.type === 'status') { renderInfo(); }
  else if (m.type === 'verified') { renderInfo(); }
  else if (m.type === 'synced') { if (!node.mempoolOn) { node.mempoolOn = true; const relays = [...new Set([...RELAYS(), 'wss://nos.lol', 'wss://relay.damus.io', 'wss://relay.nostr.band'])]; tn.followMempool({ relays }); $('i-conn').textContent = `1 mirror, ${relays.length} relays`; } renderInfo(); document.title = `Reef · txbt4 · ${n(m.height)}`; askCoins(); }
  else if (m.type === 'nostr') { node.nostr = m; renderInfo(); }
  else if (m.type === 'mempool') { $('i-mp').textContent = `${n(m.count)} (${m.stats.refused} refused, ${m.stats.dropped} dropped since the tab opened)`; $('i-mem').textContent = `${n(m.bytes)} vB, ${n(m.fees)} sat in fees`; if (document.querySelector('#nwtabs div.on')?.dataset.t === 'mempool') renderMempool(); walletMempool(); }
  else if (m.type === 'coin') { cprint(JSON.stringify(m, null, 2)); }
  else if (m.type === 'coins') { if (W && m.script === W.script) { const before = new Map(W.coins.map((c) => [c.key, c])); const first = !W.seenCoins; W.coins = m.coins; W.height = m.height;
      // a coin whose transaction spent coins of ours, with no send recorded here (the record was lost with the tab's storage, or the send was made elsewhere with the same key): it is our change, recovered from the chain
      saveSent(); for (const [k, v] of loadSeen()) if (!seen.has(k)) seen.set(k, v);
      for (const c of W.coins) if (!c.coinbase && !sent.some((s) => c.key.startsWith(s.txid)) && c.inputs?.some((k) => seen.has(k))) { const known = c.inputs.filter((k) => seen.has(k)); const inSum = known.reduce((a, k) => a + seen.get(k), 0); const partial = known.length < c.inputs.length;
        sent.push({ txid: c.key.slice(0, 64), to: '(recovered from the chain)', sats: inSum - c.value, fee: 0, partial, at: Date.now(), pending: false, height: c.height, inputs: c.inputs, tip: c.height, recovered: true });
        if (!first) notify('Sent transaction', `${partial ? 'at least ' : ''}${amt(inSum - c.value)} spent, confirmed in block ${n(c.height)} (recovered from the chain)`); }
      for (const c of W.coins) if (!seen.has(c.key)) seen.set(c.key, c.value); saveSeen(); saveSent();
      if (!first) for (const c of W.coins) if (!before.has(c.key) && !sent.some((s) => c.key.startsWith(s.txid))) notify('Incoming transaction', `${amt(c.value)} received in block ${n(c.height)}`);
      for (const s of sent) if (s.pending) { const change = W.coins.find((c) => c.key.startsWith(s.txid)); const inputsGone = s.inputs.every((k) => !W.coins.some((c) => c.key === k)); if (change || (inputsGone && W.height > s.tip)) { s.pending = false; s.height = change?.height ?? W.height; saveSent(); if (!first) notify('Sent transaction', `${amt(s.sats)} to ${s.to.slice(0, 14)}… confirmed in block ${n(s.height)}`); } }
      W.seenCoins = true; renderWallet(); } }
  else if (m.type === 'block') { const b = { hash: m.hash, confirmations: m.confirmations, height: m.height, version: m.header.version, merkleroot: m.header.merkleRoot ?? m.header.merkleroot, time: m.header.time, nonce: m.header.nonce, bits: typeof m.header.bits === 'number' ? m.header.bits.toString(16) : m.header.bits, nTx: m.nTx, previousblockhash: m.previousblockhash, nextblockhash: m.nextblockhash, size: m.size, pow: 'BLAKE2b', validated_by: 'this tab', tx: m.txids }; cprint(m.req === 'hash' ? `getblockhash ${n(m.height)} → ${m.hash}` : `getblock ${n(m.height)} →\n` + JSON.stringify(b, null, 2)); } }
// ---- the window: floating on a large screen, maximized on a small one, movable by its title bar, resizable at every
// edge, zoomed by the green dot or a double-click on the title, geometry remembered; inside Glass (?embedded=1) the host frames it
const win = $('win'); const embedded = q.get('embedded') === '1' || q.get('frame') === '0'; if (embedded) document.body.classList.add('embedded');
const geom = { get: () => { try { return JSON.parse(LS.get('reef:geometry') ?? 'null'); } catch { return null; } }, set: (g) => LS.set('reef:geometry', JSON.stringify(g)) };
function applyGeometry(g) { win.style.left = g.x + 'px'; win.style.top = g.y + 'px'; win.style.width = g.w + 'px'; win.style.height = g.h + 'px'; }
function clampGeometry(g) { const W = innerWidth, H = innerHeight; g.w = Math.max(720, Math.min(g.w, W)); g.h = Math.max(420, Math.min(g.h, H)); g.x = Math.max(0, Math.min(g.x, W - Math.min(g.w, 120))); g.y = Math.max(0, Math.min(g.y, H - 40)); return g; }
function defaultGeometry() { const w = Math.min(1180, innerWidth - 48), h = Math.min(780, innerHeight - 48); return { x: Math.round((innerWidth - w) / 2), y: Math.round((innerHeight - h) / 2), w, h }; }
function layoutWindow() { if (embedded) return; const small = innerWidth < 1100 || innerHeight < 700; const saved = geom.get(); const max = saved?.max ?? small; win.classList.toggle('max', max); if (!max) applyGeometry(clampGeometry(saved?.g ?? defaultGeometry())); }
function saveGeometry() { if (embedded) return; const max = win.classList.contains('max'); const g = max ? (geom.get()?.g ?? defaultGeometry()) : { x: win.offsetLeft, y: win.offsetTop, w: win.offsetWidth, h: win.offsetHeight }; geom.set({ max, g }); }
function toggleZoom() { if (embedded) return; const max = !win.classList.contains('max'); win.classList.toggle('max', max); if (!max) applyGeometry(clampGeometry(geom.get()?.g ?? defaultGeometry())); saveGeometry(); }
if (!embedded) {
  layoutWindow(); addEventListener('resize', () => { if (!win.classList.contains('max')) applyGeometry(clampGeometry({ x: win.offsetLeft, y: win.offsetTop, w: win.offsetWidth, h: win.offsetHeight })); });
  $('dot-zoom').onclick = (e) => { e.stopPropagation(); toggleZoom(); }; $('wtitle').ondblclick = (e) => { if (!e.target.closest('.dots, .badge')) toggleZoom(); }; $('dot-close').onclick = (e) => { e.stopPropagation(); hideWindow(); }; $('dot-min').onclick = (e) => { e.stopPropagation(); hideWindow(); };
  // drag by the title bar
  $('wtitle').onpointerdown = (e) => { if (win.classList.contains('max') || e.target.closest('.dots, .badge')) return; const sx = e.clientX - win.offsetLeft, sy = e.clientY - win.offsetTop; const move = (ev) => applyGeometry(clampGeometry({ x: ev.clientX - sx, y: ev.clientY - sy, w: win.offsetWidth, h: win.offsetHeight })); const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); saveGeometry(); }; addEventListener('pointermove', move); addEventListener('pointerup', up); e.preventDefault(); };
  // resize at any edge or corner
  win.querySelectorAll(':scope > .rs').forEach((h) => { h.onpointerdown = (e) => { if (win.classList.contains('max')) return; const d = h.dataset.rs, x0 = e.clientX, y0 = e.clientY, g0 = { x: win.offsetLeft, y: win.offsetTop, w: win.offsetWidth, h: win.offsetHeight };
    const move = (ev) => { const dx = ev.clientX - x0, dy = ev.clientY - y0; const g = { ...g0 }; if (d.includes('e')) g.w = g0.w + dx; if (d.includes('s')) g.h = g0.h + dy; if (d.includes('w')) { g.w = g0.w - dx; g.x = g0.x + dx; } if (d.includes('n')) { g.h = g0.h - dy; g.y = g0.y + dy; } if (g.w < 720) { if (d.includes('w')) g.x = g0.x + g0.w - 720; g.w = 720; } if (g.h < 420) { if (d.includes('n')) g.y = g0.y + g0.h - 420; g.h = 420; } applyGeometry(g); };
    const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); saveGeometry(); }; addEventListener('pointermove', move); addEventListener('pointerup', up); e.preventDefault(); e.stopPropagation(); }; });
}
// ---- menus, pages, node window
document.querySelectorAll('#menu > div').forEach((m) => { m.onclick = (e) => { const open = m.classList.contains('open'); document.querySelectorAll('#menu > div').forEach((x) => x.classList.remove('open')); if (!open) m.classList.add('open'); e.stopPropagation(); }; });
document.addEventListener('click', () => document.querySelectorAll('#menu > div').forEach((x) => x.classList.remove('open')));
$('m-node').onclick = () => $('nw').classList.add('open'); $('nwclose').onclick = () => $('nw').classList.remove('open');
const REPO = 'https://github.com/bitcoin-blake/reef';
$('m-readme').onclick = () => window.open(REPO + '#readme', '_blank', 'noopener'); $('m-source').onclick = () => window.open(REPO, '_blank', 'noopener'); $('m-issue').onclick = () => window.open(REPO + '/issues/new', '_blank', 'noopener');
$('about-src').href = REPO; $('about-issues').href = REPO + '/issues'; $('about-ok').onclick = () => $('about').close();
$('m-about').onclick = () => { $('about-pins').textContent = `node blaketestnode@${NODE.slice(-40, -33)} · lib sidestr/spec@${LIB.match(/@([0-9a-f]{7})/)[1]}` + (node.height != null ? ` · height ${n(node.height)}` : ''); $('about').showModal(); };
$('m-mask').onclick = () => { OPT.mask = !OPT.mask; saveOptions(); applyDisplay(); }; $('m-exit').onclick = () => hideWindow(); $('m-zoom').onclick = () => toggleZoom(); $('m-main').onclick = () => { showWindow(); $('nw').classList.remove('open'); };
// ---- the tray: closing or minimizing the window keeps the node running and leaves a small card to come back through (Knots goes to the system tray the same way); inside Glass the host is told and keeps its dock
let unseen = 0;
function hideWindow() { if (embedded) { try { parent.postMessage({ source: 'reef', type: 'minimize' }, '*'); } catch {} return; } win.style.display = 'none'; unseen = 0; $('tray-badge').hidden = true; $('tray').hidden = false; trayRefresh(); }
function showWindow() { win.style.display = ''; $('tray').hidden = true; unseen = 0; $('tray-badge').hidden = true; }
function trayRefresh() { if ($('tray').hidden) return; const sd = tn.seeding?.t ? ` · seeding to ${tn.seeding.t.wires.filter((w) => !w.destroyed && w.type !== 'webSeed').length}` : ''; $('tray-l').textContent = node.error ? 'error' : node.synced ? `up to date · ${n(node.height)}${sd}` : node.phase === 'fetch' ? 'fetching the snapshot' : node.phase === 'hash' ? 'checking the snapshot' : node.phase === 'verify' ? 'verifying the snapshot' : node.phase === 'sync' ? `syncing · ${n(node.height ?? 0)}` : 'starting'; $('tray-dot').className = node.error ? 'bad' : node.synced ? 'ok' : 'sync'; }
$('tray').onclick = () => showWindow(); setInterval(trayRefresh, 1000);
document.addEventListener('keydown', (e) => { if (e.ctrlKey && e.shiftKey && e.key.toLowerCase() === 'm') { e.preventDefault(); $('m-mask').onclick(); } if (e.ctrlKey && !e.shiftKey && e.key.toLowerCase() === 'm') { e.preventDefault(); $('m-main').onclick(); } });
$('m-wipe').onclick = () => { if (confirm('Remove the snapshot and its index from this tab\'s storage? The next visit fetches it again.')) tn.wipe(); };
// ---- Options: one dialog, four tabs, values kept in reef:options (the snapshot and blocks URLs keep their own keys)
const opt = { snapshot: SNAP_URL, blocks: BLOCKS_URL };
document.querySelectorAll('#otabs div').forEach((d) => { d.onclick = () => showOptionsTab(d.dataset.o); });
function showOptionsTab(t) { document.querySelectorAll('#otabs div').forEach((x) => x.classList.toggle('on', x.dataset.o === t)); document.querySelectorAll('.op').forEach((p) => p.classList.toggle('on', p.id === 'o-' + t)); }
function fillOptions(o = OPT, urls = opt) { $('o-snapshot').value = urls.snapshot; $('o-blocks').value = urls.blocks; $('o-feerate').value = o.feeRate; $('o-notify').checked = !!o.notify; $('o-torrent').checked = !!o.torrent; const mr = mempoolRate(); $('o-feeuse').style.display = mr != null ? '' : 'none'; $('o-feesugg').textContent = mr != null ? `the tab's mempool: ${node.mempool.count} transaction${node.mempool.count === 1 ? '' : 's'}, median ${mr} sat/vB; Knots shows the rate as tBTC/kvB` : 'Knots shows this as tBTC/kvB; 1 sat/vB is what txbt4 blocks take today'; $('o-seed').checked = !!o.seed; $('o-seednote').textContent = tn.seeding?.t ? `seeding now: ${tn.seeding.t.wires.filter((w) => !w.destroyed).length} peer(s), ${mib(tn.seeding.t.uploaded)} uploaded` : fileReady() ? 'the snapshot is here; turn this on to serve it' : 'starts once the snapshot is here and checked'; $('o-relays').value = (o.relays ?? DEFAULT_RELAYS).join('\n'); $('o-unit').value = o.unit; $('o-mask').checked = !!o.mask; $('o-mirror').textContent = urls.blocks + '.dat';
  $('o-address').value = W?.address ?? '…'; $('o-key').value = '•'.repeat(64); $('o-showkey').textContent = 'Show'; $('o-importkey').value = ''; $('o-keywarn').textContent = ''; $('o-wipenote').textContent = ''; $('o-geomnote').textContent = '';
  const perm = 'Notification' in window ? Notification.permission : 'unsupported'; $('o-perm').textContent = perm === 'granted' ? 'the browser allows notifications from this page' : perm === 'denied' ? 'the browser has blocked notifications from this page; change that in the site settings' : perm === 'default' ? 'the browser has not been asked yet' : 'this browser has no notifications'; $('o-allow').style.display = perm === 'default' ? '' : 'none';
  const lp = o.lastPublish; $('o-relaylast').textContent = lp ? Object.entries(lp.results).map(([u, r]) => `${u.replace('wss://', '')} ${r === 'ok' ? 'ok' : 'failed'}`).join(', ') + ` (${fmt(Math.floor(lp.at / 1000))})` : 'none yet';
  navigator.storage?.estimate?.().then((e) => { $('o-storage').textContent = `${mib(e.usage ?? 0)} in use`; }).catch(() => { $('o-storage').textContent = 'unknown'; }); }
function openOptions(tab = 'main') { fillOptions(); showOptionsTab(tab); $('options').showModal(); }
$('m-options').onclick = () => openOptions();
$('o-cancel').onclick = () => $('options').close(); $('o-reset').onclick = () => fillOptions(OPT_DEFAULTS, { snapshot: 'https://melvin.me/public/txbt4/utxo-knots-150307.dat', blocks: 'https://melvin.me/public/txbt4/txbt4-blocks' });
$('o-feeuse').onclick = () => { const r = mempoolRate(); if (r != null) $('o-feerate').value = r; }; $('o-allow').onclick = () => { Notification.requestPermission().then(() => fillOptions()); };
$('o-showkey').onclick = () => { const shown = $('o-key').value !== '•'.repeat(64); $('o-key').value = shown ? '•'.repeat(64) : (W?.key ?? ''); $('o-showkey').textContent = shown ? 'Show' : 'Hide'; };
$('o-copykey').onclick = async () => { try { await navigator.clipboard.writeText(W?.key ?? ''); $('o-copykey').textContent = 'Copied'; setTimeout(() => { $('o-copykey').textContent = 'Copy'; }, 1500); } catch {} };
$('o-newkey').onclick = () => { if (!W) return; $('o-importkey').value = W.signer.randomKey(); $('o-keywarn').textContent = 'a new key: press OK to use it in this tab; copy the current key first if it holds coins'; };
$('o-importkey').oninput = () => { const v = $('o-importkey').value.trim(); $('o-keywarn').textContent = v && !/^[0-9a-f]{64}$/i.test(v) ? 'a key is 64 hex characters' : v ? 'press OK to replace the key in this tab; coins at the old address stay there' : ''; };
$('o-wipe').onclick = () => { if ($('o-wipe').dataset.armed) { tn.wipe(); $('o-wipenote').textContent = 'wiping; the next visit fetches the snapshot again'; delete $('o-wipe').dataset.armed; } else { $('o-wipe').dataset.armed = '1'; $('o-wipenote').textContent = 'press again to remove the snapshot and its index from this tab'; } };
$('o-resetgeom').onclick = () => { try { localStorage.removeItem('reef:geometry'); localStorage.removeItem('reef:node-geometry'); } catch {} $('o-geomnote').textContent = 'reset; takes effect on reload'; };
$('o-ok').onclick = () => { const key = $('o-importkey').value.trim().toLowerCase(); if (key && !/^[0-9a-f]{64}$/.test(key)) { showOptionsTab('wallet'); $('o-keywarn').textContent = 'a key is 64 hex characters'; return; }
  const relays = $('o-relays').value.split(/\s+/).map((r) => r.trim()).filter((r) => /^wss?:\/\//.test(r)); OPT.feeRate = Math.max(1, Math.round(Number($('o-feerate').value) || 1)); OPT.notify = $('o-notify').checked; OPT.torrent = $('o-torrent').checked; OPT.seed = $('o-seed').checked; tn.setTorrent(OPT.torrent); tn.setSeed(OPT.seed); OPT.relays = relays.length ? relays : DEFAULT_RELAYS; OPT.unit = $('o-unit').value; OPT.mask = $('o-mask').checked; saveOptions();
  const snap = $('o-snapshot').value.trim(), blocks = $('o-blocks').value.trim(); const reload = snap !== opt.snapshot || blocks !== opt.blocks || !!key;
  if (snap) LS.set('reef:snapshot', snap); if (blocks) LS.set('reef:blocks', blocks); if (key) LS.set('reef:key', key);
  $('options').close(); if (reload) { location.search = ''; return; } $('sendunit').value = String(unit().div); applyDisplay(); renderPeers(); };
document.addEventListener('keydown', (e) => { if (e.ctrlKey && e.shiftKey && e.key.toLowerCase() === 'd') { e.preventDefault(); $('nw').classList.toggle('open'); } });
document.querySelectorAll('.tool button[data-p]').forEach((b) => { b.onclick = () => { document.querySelectorAll('.tool button[data-p]').forEach((x) => x.classList.toggle('on', x === b)); document.querySelectorAll('.page').forEach((p) => p.classList.toggle('on', p.id === 'p-' + b.dataset.p)); }; });
document.querySelectorAll('#nwtabs div').forEach((d) => { d.onclick = () => { document.querySelectorAll('#nwtabs div').forEach((x) => x.classList.toggle('on', x === d)); document.querySelectorAll('.tp').forEach((p) => p.classList.toggle('on', p.id === 't-' + d.dataset.t)); if (d.dataset.t === 'traffic') drawTraffic(); if (d.dataset.t === 'console') $('cin').focus(); if (d.dataset.t === 'peers') renderPeers(); if (d.dataset.t === 'mempool') renderMempool(); }; });
(() => { const nw = $('nw'), t = $('nwt'); try { const g = JSON.parse(LS.get('reef:node-geometry') ?? 'null'); if (g) { nw.style.left = g.x + 'px'; nw.style.top = g.y + 'px'; nw.style.width = g.w + 'px'; nw.style.height = g.h + 'px'; } } catch {} const save = () => LS.set('reef:node-geometry', JSON.stringify({ x: nw.offsetLeft, y: nw.offsetTop, w: nw.offsetWidth, h: nw.offsetHeight }));
  t.onpointerdown = (e) => { if (e.target.id === 'nwclose') return; const sx = e.clientX - nw.offsetLeft, sy = e.clientY - nw.offsetTop; const move = (ev) => { nw.style.left = Math.max(0, Math.min(ev.clientX - sx, innerWidth - 120)) + 'px'; nw.style.top = Math.max(0, Math.min(ev.clientY - sy, innerHeight - 40)) + 'px'; }; const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); save(); }; addEventListener('pointermove', move); addEventListener('pointerup', up); e.preventDefault(); };
  nw.querySelector('.rs.se').onpointerdown = (e) => { const x0 = e.clientX, y0 = e.clientY, w0 = nw.offsetWidth, h0 = nw.offsetHeight; const move = (ev) => { nw.style.width = Math.max(560, w0 + ev.clientX - x0) + 'px'; nw.style.height = Math.max(320, h0 + ev.clientY - y0) + 'px'; }; const up = () => { removeEventListener('pointermove', move); removeEventListener('pointerup', up); save(); }; addEventListener('pointermove', move); addEventListener('pointerup', up); e.preventDefault(); e.stopPropagation(); }; })();
// ---- the wallet: one key kept in this tab; coins from the tab's own UTXO set (created since the snapshot); sends built,
// signed and checked here, then published as a kind 23503 event for a sidestr producer's node to broadcast
let W = null; const loadSent = () => { try { return JSON.parse(LS.get('reef:sent') ?? '[]'); } catch { return []; } }; const sent = loadSent();
// two tabs of the same origin share the storage but not their memory: merge with what is stored before writing, so neither tab drops the other's send
const saveSent = () => { for (const o of loadSent()) { const m = sent.find((x) => x.txid === o.txid); if (!m) sent.push(o); else if (m.pending && !o.pending) Object.assign(m, o); } sent.sort((a, b) => (a.at ?? 0) - (b.at ?? 0)); LS.set('reef:sent', JSON.stringify(sent.slice(-50))); }; // sent: { txid, to, sats, fee, at, event, relays, pending, inputs, tip }, kept across reloads so a pending send can be confirmed later
function unit() { const UNITS = { tbtc: { label: 'tBTC', div: 1e8, dp: 8 }, mtbtc: { label: 'mtBTC', div: 1e5, dp: 5 }, sats: { label: 'sat', div: 1, dp: 0 } }; return UNITS[OPT.unit] ?? UNITS.tbtc; }
function money(sats) { if (OPT.mask) return '•••••'; const u = unit(); const v = Math.abs(sats) / u.div; return (sats < 0 ? '-' : '') + (u.dp ? v.toFixed(u.dp) : n(Math.round(v))); }
function amt(sats) { return `${money(sats)} ${unit().label}`; }
function applyDisplay() { document.querySelectorAll('.unit').forEach((e) => { e.textContent = unit().label; }); $('m-mask-tick').textContent = OPT.mask ? '✓' : ''; const rate = Math.max(1, Number(OPT.feeRate) || 1); $('feerate').textContent = `${(rate * 1000 / 1e8).toFixed(8)} tBTC/kvB (${rate} sat/vB)`; if (W) renderWallet(); }
async function walletInit() {
  const [{ makeSigner }, txsign, addr, relay, secp, hash, { createKernel }, { knotsBlake2b }] = await Promise.all([import(`${LIB}/schnorr.mjs`), import(`${LIB}/txsign.mjs`), import(`${LIB}/address.mjs`), import(`${LIB}/relay.mjs`), import(`${CDN}/codec/secp256k1.js`), import(`${CDN}/codec/hash.js`), import(`${CDN}/codec/kernel.js`), import(`${CDN}/codec/overlays/knots-blake2b.js`)]);
  const j = async (p) => (await fetch(`${CDN}/${p}`)).json();
  const k = createKernel({ core: await j('schema/core.jsonld'), proof: await j('schema/proof.jsonld'), script: await j('schema/script.jsonld'), chain: await j('schema/chain.jsonld'), validate: await j('schema/validate.jsonld'), network: 'btc:testnet4-blake2b', overlays: [knotsBlake2b(await j('schema/overlays/knots-blake2b.jsonld'))] });
  const signer = makeSigner({ hash, secp }); let key = LS.get('reef:key'); if (!/^[0-9a-f]{64}$/.test(key ?? '')) { key = signer.randomKey(); LS.set('reef:key', key); }
  const pub = signer.pubkeyOf(key), script = '5120' + pub, address = addr.scriptToAddress(script, 'tb');
  W = { k, hash, secp, signer, txsign, addr, relay, events: relay.makeEvents({ signer, hash }), key, pub, script, address, coins: [], height: null };
  seen = loadSeen();
  $('rcvaddr').value = address; try { const qr = qrcode(0, 'M'); qr.addData('bitcoin:' + address); qr.make(); $('rcvqr').innerHTML = qr.createSvgTag({ cellSize: 4, margin: 0 }); } catch {}
  $('rcvcopy').onclick = async () => { try { await navigator.clipboard.writeText(address); $('rcvcopy').textContent = 'Copied'; setTimeout(() => { $('rcvcopy').textContent = 'Copy'; }, 1500); } catch {} };
  $('sendall').onclick = () => { const b = balances(); $('sendamt').value = (Math.max(0, b.available - 500) / Number($('sendunit').value)).toString(); };
  $('sendclear').onclick = () => { $('sendto').value = ''; $('sendamt').value = '0.00000000'; $('sendout').textContent = ''; };
  $('sendgo').onclick = () => send($('sendto').value.trim(), Math.round(Number($('sendamt').value) * Number($('sendunit').value)));
  $('sendpaste').onclick = async () => { try { $('sendto').value = (await navigator.clipboard.readText()).trim(); } catch { $('sendout').textContent = 'the browser did not allow reading the clipboard'; } };
  $('feechoose').onclick = () => openOptions('wallet'); $('sendunit').value = String(unit().div); $('sendamt').value = unit().dp ? (0).toFixed(unit().dp) : '0'; applyDisplay();
  renderWallet(); if (node.synced) askCoins();
}
function askCoins() { if (W) post({ type: 'coins', script: W.script }); }
let seen = new Map(); const seenKey = () => 'reef:seen:' + W.script.slice(4, 20); const loadSeen = () => { try { return new Map(JSON.parse(LS.get(seenKey()) ?? '[]')); } catch { return new Map(); } };
const saveSeen = () => { for (const [k, v] of loadSeen()) if (!seen.has(k)) seen.set(k, v); LS.set(seenKey(), JSON.stringify([...seen].slice(-500))); }; // every coin of ours this tab has seen, key → value, so change can be told from a receipt after a reload
const reserved = () => new Set(sent.filter((s) => s.pending).flatMap((s) => s.inputs ?? []));
const mature = (c) => !c.coinbase || (W.height != null && W.height + 1 - c.height >= 100);
function balances() { let available = 0, immature = 0; const held = reserved(); for (const c of W.coins) { if (held.has(c.key)) continue; (mature(c) ? (available += c.value) : (immature += c.value)); } const pending = sent.filter((s) => s.pending).reduce((a, s) => a - s.sats - s.fee, 0) + unconfirmedIn().reduce((a, x) => a + x.toUs, 0); return { available, immature, pending, total: available + immature + pending }; }
// what the mempool says about this wallet: incoming unconfirmed coins (a notice once each), and our pending sends now seen
let mpSeen = new Set();
function ourTx(t) { const mine = (k) => seen.has(k) || W.coins.some((c) => c.key === k); return { spendsOurs: t.inputs.some(mine), toUs: t.outputs.reduce((a, o) => a + (o.scriptPubKey === W.script ? o.value : 0), 0) }; }
function walletMempool() { if (!W || !node.mempool) return; const first = !W.mpReady; W.mpReady = true;
  for (const t of node.mempool.txs) { const { spendsOurs, toUs } = ourTx(t); const s = sent.find((x) => x.txid === t.txid); if (s) { if (s.pending && !s.inMempool) { s.inMempool = true; saveSent(); } continue; }
    if (spendsOurs) { const known = t.inputs.filter((k) => seen.has(k)); const inSum = known.reduce((a, k) => a + seen.get(k), 0); sent.push({ txid: t.txid, to: '(seen in the mempool)', sats: Math.max(0, inSum - toUs), fee: 0, partial: known.length < t.inputs.length, at: Date.now(), pending: true, inMempool: true, height: null, inputs: t.inputs, tip: node.height, recovered: true }); saveSent(); continue; }
    if (toUs && !mpSeen.has(t.txid)) { mpSeen.add(t.txid); if (!first) notify('Incoming transaction', `${amt(toUs)} received, unconfirmed`); } }
  renderWallet(); }
function unconfirmedIn() { if (!W || !node.mempool) return []; return node.mempool.txs.map((t) => ({ t, ...ourTx(t) })).filter((x) => x.toUs && !x.spendsOurs && !sent.some((s) => s.txid === x.t.txid)); }
function renderWallet() { if (!W) return; const b = balances(); $('avail').textContent = amt(b.available); $('immature').textContent = amt(b.immature); $('pending').textContent = amt(b.pending); $('total').textContent = amt(b.total); $('sendbal').textContent = amt(b.available);
  const rows = [...unconfirmedIn().map((x) => ({ kind: 'in', label: 'Received with (unconfirmed)', addr: W.address, sats: x.toUs, height: null, pending: true, txid: x.t.txid })), ...sent.map((s) => ({ kind: 'out', label: (s.recovered ? (s.partial ? 'Sent (at least)' : 'Sent') : 'Sent to') + (s.pending && s.inMempool ? ' (in the mempool)' : ''), addr: s.to, sats: -(s.sats + s.fee), height: s.height ?? null, pending: s.pending, txid: s.txid })), ...W.coins.filter((c) => !sent.some((s) => c.key.startsWith(s.txid))).map((c) => ({ kind: 'in', label: c.coinbase ? 'Mined' : 'Received with', addr: W.address, sats: c.value, height: c.height, txid: c.key.split(':')[0], conf: W.height != null ? W.height - c.height + 1 : null }))].sort((a, b) => (b.height ?? 1e9) - (a.height ?? 1e9));
  $('recent').innerHTML = rows.length ? rows.slice(0, 6).map((r) => `<div class="r"><span title="${r.pending ? 'pending: published, not yet in a block' : (r.conf ?? '') + ' confirmations'}">${r.pending ? '⏳' : r.label === 'Mined' ? '⛏' : r.kind === 'in' ? '⬇' : '⬆'}</span><span>${r.height ? 'block ' + n(r.height) : 'pending'}</span><span class="addr" title="${r.txid}"><a href="https://mempool.guide/testnet4/tx/${r.txid}" target="_blank" rel="noopener" style="color:inherit">${r.label} · ${r.addr}</a></span><span class="amt ${r.pending ? 'pend' : r.kind === 'in' ? 'in' : 'out'}">${amt(r.sats)}</span></div>`).join('') : '<div class="r"><span></span><span class="mut" style="grid-column:2/5">no coins yet: send some to the address on the Receive page</span></div>';
  $('txrows').innerHTML = rows.length ? rows.map((r) => `<tr><td title="${r.pending ? 'pending' : (r.conf ?? '') + ' confirmations'}">${r.pending ? '⏳' : '✔'}</td><td>${r.height ? 'block ' + n(r.height) : 'pending'}</td><td>${r.label}</td><td class="addr" style="max-width:420px" title="${r.txid}"><a href="https://mempool.guide/testnet4/tx/${r.txid}" target="_blank" rel="noopener" style="color:inherit">${r.addr}</a></td><td class="amt ${r.kind === 'in' ? 'in' : 'out'}">${money(r.sats)}</td></tr>`).join('') : '<tr><td colspan="5" class="mut">no transactions since the snapshot</td></tr>';
  $('rcvrows').innerHTML = W.coins.length ? W.coins.slice().sort((a, b) => b.height - a.height).map((c) => `<tr><td>${n(c.height)}</td><td class="mono"><a href="https://mempool.guide/testnet4/tx/${c.key.split(':')[0]}" target="_blank" rel="noopener" style="color:inherit">${c.key.slice(0, 20)}…:${c.key.split(':')[1]}</a></td><td>${W.height != null ? n(W.height - c.height + 1) : '…'}${c.coinbase && !mature(c) ? ' (coinbase, immature)' : ''}</td><td class="amt">${money(c.value)}</td></tr>`).join('') : '<tr><td colspan="4" class="mut">nothing received since the snapshot</td></tr>'; }
// build, sign, check and publish a payment; returns { txid, event, results }
async function send(to, sats) { const out = $('sendout'); const fail = (m) => { out.innerHTML = `<span class="bad">${m}</span>`; throw new Error(m); };
  if (!W) fail('the wallet is not ready'); if (!node.synced) fail('wait for the node to be up to date'); const dec = W.addr.decodeAddress(to); if (!dec || dec.hrp !== 'tb') fail('not a txbt4 address (tb1…)'); if (!(sats >= 546)) fail('amount too small (at least 546 sats)');
  const held = reserved(); const coins = W.coins.filter((c) => mature(c) && !held.has(c.key)).sort((a, b) => b.value - a.value); const RATE = Math.max(1, Number(OPT.feeRate) || 1); let picked = [], inSum = 0, fee = 0;
  for (const c of coins) { picked.push(c); inSum += c.value; fee = Math.ceil(RATE * (11 + picked.length * 58 + 2 * 43)); if (inSum >= sats + fee) break; }
  if (inSum < sats + fee) fail(`not enough mature coins: ${money(inSum)} available, ${money(sats + fee)} needed with the fee`);
  const change = inSum - sats - fee; const outputs = [{ value: sats, scriptPubKey: dec.script }]; if (change >= 330) outputs.push({ value: change, scriptPubKey: W.script }); else fee += change;
  const tx = { version: 2, inputs: picked.map((c) => ({ prevout: { txid: c.key.split(':')[0], vout: Number(c.key.split(':')[1]) }, scriptSig: '', sequence: 0xfffffffd })), outputs, lockTime: 0, witness: [] };
  const prevouts = picked.map((c) => ({ value: c.value, scriptPubKey: W.script })); W.txsign.signKeyPath({ k: W.k, hash: W.hash, signer: W.signer }, tx, prevouts, W.key);
  if (!W.txsign.verifyKeyPath({ k: W.k, hash: W.hash, secp: W.secp }, tx, prevouts, W.pub)) fail('the signature did not verify');
  const hex = W.k.codec.encodeHex('Transaction', tx), txid = W.k.codec.txid(tx); out.textContent = `built ${txid.slice(0, 16)}… (${picked.length} input${picked.length === 1 ? '' : 's'}, fee ${fee} sats); publishing…`;
  const event = W.events.parentTxEvent(W.signer.randomKey(), 'sidestr:tally', hex); let results = {}; try { results = await W.relay.publish({ relays: RELAYS(), event }); OPT.lastPublish = { at: Date.now(), results }; saveOptions(); } catch (e) { fail('publish failed: ' + e.message); }
  const okRelays = Object.entries(results).filter(([, r]) => r === 'ok').map(([u]) => u); if (!okRelays.length) fail('no relay accepted the event: ' + JSON.stringify(results));
  sent.push({ txid, to, sats, fee, at: Date.now(), event: event.id, relays: okRelays, pending: true, inputs: picked.map((c) => c.key), tip: W.height }); saveSent(); for (const c of picked) seen.set(c.key, c.value); saveSeen(); for (const c of picked) W.coins = W.coins.filter((x) => x !== c); renderWallet();
  out.innerHTML = `<span class="good">published</span> · txid <span class="mono">${txid}</span> · event ${event.id.slice(0, 12)}… on ${okRelays.length} relay${okRelays.length === 1 ? '' : 's'} · it appears here once a block carrying it is validated`; cprint(`· sent ${amt(sats)} to ${to} (fee ${fee} sats): ${txid}`, 'log'); return { txid, event, results }; }
// ---- notices: Knots shows a tray balloon for a transaction; here a toast in the page and, if allowed, a browser notification
function notify(title, body) { cprint(`· ${title}: ${body}`, 'log'); if (!$('tray').hidden) { unseen++; $('tray-badge').textContent = unseen; $('tray-badge').hidden = false; } const el = document.createElement('div'); el.className = 'toast'; el.innerHTML = `<b>${title}</b><br>${body}`; $('toasts').appendChild(el); setTimeout(() => { el.classList.add('out'); setTimeout(() => el.remove(), 400); }, 6000);
  if (OPT.notify && 'Notification' in window) { if (Notification.permission === 'granted') new Notification(`Reef · ${title}`, { body, icon: 'og.png' }); else if (Notification.permission === 'default') Notification.requestPermission().then((p) => { if (p === 'granted') new Notification(`Reef · ${title}`, { body }); }); } }
// ---- peers: what the tab actually reads from
function renderMempool() { const m = node.mempool; if (!m) return; const now = Math.floor(Date.now() / 1000); const rates = m.txs.map((t) => t.feeRate).sort((a, b) => a - b); const med = rates.length ? rates[Math.floor(rates.length / 2)] : null;
  $('mp-sum').textContent = `${n(m.count)} transaction${m.count === 1 ? '' : 's'} · ${n(m.bytes)} vB · ${n(m.fees)} sat in fees${med != null ? ` · median ${med.toFixed(1)} sat/vB` : ''} · at height ${n(m.height ?? 0)}`;
  $('mprows').innerHTML = m.txs.length ? m.txs.map((t) => { const o = W ? ourTx(t) : { spendsOurs: false, toUs: 0 }; const age = Math.max(0, now - t.at); return `<tr><td class="mono" title="${t.txid}">${t.txid.slice(0, 16)}…</td><td>${age < 60 ? age + ' s' : age < 3600 ? Math.round(age / 60) + ' min' : (age / 3600).toFixed(1) + ' h'}</td><td class="amt">${n(t.vsize)}</td><td class="amt">${n(t.fee)}</td><td class="amt">${t.feeRate.toFixed(1)}</td><td>${o.spendsOurs ? 'from us' : o.toUs ? 'to us: ' + amt(o.toUs) : ''}</td></tr>`; }).join('') : '<tr><td colspan="6" class="mut">empty</td></tr>'; }
function mempoolRate() { const m = node.mempool; if (!m || !m.txs.length) return null; const r = m.txs.map((t) => t.feeRate).sort((a, b) => a - b); return Math.max(1, Math.ceil(r[Math.floor(r.length / 2)])); }
function renderPeers() { const rows = [[BLOCKS_URL.replace(/^https?:\/\//, ''), 'mirror', 'block file, Range', `${(node.recv / 1e6).toFixed(2)} MB`], ...['wss://nos.lol', 'wss://relay.damus.io', 'wss://relay.nostr.band'].map((r) => [r.replace('wss://', ''), 'relay', 'NIP-333 tip events', '—']), ...RELAYS().map((r) => [r.replace('wss://', ''), 'relay', 'sends (kind 23503)', '—']), ...(tn.seeding?.t ? tn.seeding.t.wires.filter((w) => !w.destroyed).map((w) => [w.peerId ? w.peerId.slice(0, 20) + '…' : '(peer)', w.type === 'webSeed' ? 'webseed' : 'swarm peer', 'snapshot pieces (WebRTC)', `${(w.uploaded / 1e6).toFixed(2)} MB sent`]) : [])];
  $('peerrows').innerHTML = rows.map((p, i) => `<tr data-i="${i}"><td>${i + 1}</td><td>${Math.round((Date.now() - T0) / 60000)} min</td><td>Outbound</td><td>${p[2]}</td><td>${p[1]}</td><td>—</td><td>${p[1] === 'swarm peer' ? p[3].replace(' sent', '') : '0 MB'}</td><td>${p[1] === 'swarm peer' ? '—' : p[3]}</td><td class="mono">${p[0]}</td></tr>`).join('');
  document.querySelectorAll('#peerrows tr').forEach((tr) => { tr.onclick = () => { document.querySelectorAll('#peerrows tr').forEach((x) => x.classList.toggle('sel', x === tr)); const p = rows[tr.dataset.i]; $('pd').innerHTML = `<div class="kv"><span class="l">Peer</span><span class="v">${p[0]}</span><span class="l">Kind</span><span class="v">${p[1]}: ${p[2]}</span><span class="l">Note</span><span class="v">a tab does not speak the peer-to-peer protocol; it reads a mirror's block file and the signer's tip announcements, and validates everything itself</span></div>`; }; }); }
renderPeers();
// ---- console, answering from the tab's state in the shapes Knots uses
const cout = $('cout'), cin = $('cin'); const chist = []; let hi = 0; const err = (code, message) => ({ __err: { code, message } });
function cprint(s, cls) { const el = document.createElement('span'); if (cls) el.className = cls; el.textContent = s + '\n'; cout.appendChild(el); cout.scrollTop = cout.scrollHeight; }
const ANS = {
  getblockchaininfo: () => ({ chain: 'testnet4', blocks: node.height, headers: node.height, bestblockhash: node.hash, time: node.time, verificationprogress: node.synced ? 1 : 0, initialblockdownload: !node.synced, pruned: false, size_on_disk: node.st?.dat ?? null, warnings: [`synced from the verified UTXO snapshot at 150307 (hash_serialized_3 ${node.hs ? node.hs.slice(0, 16) + '…' : 'pending'}); BLAKE2b blocks since the fork validated in this tab`] }),
  getblockcount: () => node.height, getbestblockhash: () => node.hash,
  getsnapshotinfo: () => ({ base_height: 150307, base_hash: node.st?.expect.baseHash, hash_serialized_3: node.hs ?? node.st?.expect.txoutsetHash, verified: node.hsOk ?? (node.st?.idx > 0), sha256: node.sha ?? node.st?.sha ?? null, coins: node.coins ?? node.st?.expect.coins, txids: node.txids ?? null, bytes: node.st?.expect.bytes, source: SNAP_URL, sync_history: Object.fromEntries(node.hist.map(([k, v]) => [k, +(v / 1000).toFixed(1)])) }),
  gettxoutsetinfo: () => ({ height: node.height, bestblock: node.hash, txouts: node.coins, hash_serialized_3: node.hs ?? '(not recomputed at the tip; the snapshot base is)', note: 'the count is the snapshot\'s plus the blocks applied since; a full recount at the tip is not offered by the tab yet' }),
  getnetworkinfo: () => ({ version: 1, subversion: '/Reef:0.1/', networkactive: true, connections: 4, connections_in: 0, connections_out: 4, networks: [{ name: 'mirror', reachable: true, url: BLOCKS_URL }, { name: 'nostr', reachable: true, relays: ['wss://nos.lol', 'wss://relay.damus.io', 'wss://relay.nostr.band'] }], warnings: ['a tab reads a mirror and relays; it does not speak the peer-to-peer protocol'] }),
  getpeerinfo: () => [{ id: 0, addr: BLOCKS_URL, kind: 'mirror', bytesrecv: node.recv }, ...['wss://nos.lol', 'wss://relay.damus.io', 'wss://relay.nostr.band'].map((r, i) => ({ id: i + 1, addr: r, kind: 'relay' }))],
  getmempoolinfo: () => node.mempool ? { loaded: true, size: node.mempool.count, bytes: node.mempool.bytes, usage: node.mempool.bytes, total_fee: node.mempool.fees / 1e8, mempoolminfee: 0.00001, minrelaytxfee: 0.00001, refused: node.mempool.stats.refused, dropped: node.mempool.stats.dropped, note: 'this tab\'s own mempool: transactions heard on relays and validated here' } : err(-28, 'the mempool is followed once the tab is up to date'),
  getrawmempool: (v) => node.mempool ? (v === 'true' || v === true ? Object.fromEntries(node.mempool.txs.map((t) => [t.txid, { vsize: t.vsize, fees: { base: t.fee / 1e8 }, time: t.at, feerate: t.feeRate }])) : node.mempool.txs.map((t) => t.txid)) : err(-28, 'the mempool is followed once the tab is up to date'),
  getmempoolentry: (txid) => { const t = node.mempool?.txs.find((x) => x.txid === txid); return t ? { txid: t.txid, vsize: t.vsize, fees: { base: t.fee / 1e8 }, time: t.at, feerate: t.feeRate, inputs: t.inputs, outputs: t.outputs } : err(-5, 'Transaction not in mempool'); },
  getnostrtip: () => node.nostr ? { height: node.nostr.height, hash: node.nostr.hash, relay: node.nostr.relay, created_at: node.nostr.created_at, agree: node.nostr.agree, live: !!node.nostr.live } : err(-1, 'no tip announcement seen yet'),
  gettxout: (a) => { if (!/^[0-9a-f]{64}$/i.test(a[0] ?? '') || !/^\d+$/.test(a[1] ?? '')) return err(-8, 'gettxout "txid" n'); post({ type: 'coin', key: `${a[0].toLowerCase()}:${a[1]}` }); return '(asked the node; the answer prints when it arrives)'; },
  getblockhash: (a) => { const h = Number(a[0]); if (!/^\d+$/.test(a[0] ?? '')) return err(-8, 'getblockhash height'); if (h === 150307) return node.st?.expect.baseHash; if (!node.synced) return err(-28, 'still syncing'); if (h < 150308 || h > node.height) return err(-8, `Block height out of range: this tab holds ${n(150308)} to ${n(node.height)} (the BLAKE2b blocks; the snapshot base is 150307)`); post({ type: 'block', height: h, req: 'hash' }); return '(reading the block file…)'; },
  getblock: (a) => { if (!node.synced) return err(-28, 'still syncing'); if (/^[0-9a-f]{64}$/i.test(a[0] ?? '')) post({ type: 'block', hash: a[0].toLowerCase(), req: 'block' }); else if (/^\d+$/.test(a[0] ?? '')) post({ type: 'block', height: Number(a[0]), req: 'block' }); else return err(-8, 'getblock "blockhash" (or a height)'); return '(reading the block file…)'; },
  getblockheader: (a) => ANS.getblock(a),
  uptime: () => Math.floor((Date.now() - T0) / 1000),
  getbalance: () => W ? balances().available / 1e8 : err(-18, 'wallet not ready'), getwalletinfo: () => W ? { walletname: 'reef', format: 'one key in this tab', balance: balances().available / 1e8, unconfirmed_balance: balances().pending / 1e8, immature_balance: balances().immature / 1e8, txcount: W.coins.length + sent.length, keypoolsize: 1, descriptors: false, note: 'coins created since the snapshot; the tab does not scan the snapshot itself for a script' } : err(-18, 'wallet not ready'),
  getnewaddress: () => W ? W.address : err(-18, 'wallet not ready'), getaddressinfo: (a) => { if (!W) return err(-18, 'wallet not ready'); const d = W.addr.decodeAddress(a[0] ?? ''); return d ? { address: a[0], scriptPubKey: d.script, ismine: d.script === W.script, iswitness: true, witness_version: d.version, witness_program: d.program } : err(-5, 'Invalid address'); },
  listunspent: () => W ? W.coins.map((c) => ({ txid: c.key.split(':')[0], vout: Number(c.key.split(':')[1]), address: W.address, scriptPubKey: W.script, amount: c.value / 1e8, confirmations: W.height != null ? W.height - c.height + 1 : null, spendable: mature(c), coinbase: c.coinbase, inputs: c.inputs ?? [] })) : err(-18, 'wallet not ready'),
  sendtoaddress: (a) => { if (!W) return err(-18, 'wallet not ready'); if (!a[0] || !(Number(a[1]) > 0)) return err(-8, 'sendtoaddress "address" amount'); send(a[0], Math.round(Number(a[1]) * 1e8)).then((r) => cprint(r.txid)).catch((e) => cprint(e.message, 'err')); return '(building, signing and publishing…)'; },
  listsent: () => sent,
  help: () => `== Blockchain ==\ngetbestblockhash\ngetblock "blockhash" | height\ngetblockchaininfo\ngetblockcount\ngetblockhash height\ngetsnapshotinfo\ngettxout "txid" n\ngettxoutsetinfo\n\n== Control ==\nhelp\nuptime\n\n== Mempool ==\ngetmempoolentry "txid"\ngetmempoolinfo\ngetrawmempool [verbose]\n\n== Network ==\ngetnetworkinfo\ngetnostrtip\ngetpeerinfo\n\n== Wallet ==\ngetaddressinfo "address"\ngetbalance\ngetnewaddress\ngetwalletinfo\nlistsent\nlistunspent\nsendtoaddress "address" amount`,
};
cin.onkeydown = (e) => { if (e.key === 'ArrowUp') { hi = Math.max(0, hi - 1); cin.value = chist[hi] ?? ''; } else if (e.key === 'ArrowDown') { hi = Math.min(chist.length, hi + 1); cin.value = chist[hi] ?? ''; } else if (e.ctrlKey && e.key.toLowerCase() === 'l') { e.preventDefault(); cout.textContent = ''; } else if (e.key === 'Enter') { const line = cin.value.trim(); cin.value = ''; if (!line) return; chist.push(line); hi = chist.length; cprint('> ' + line, 'cmd'); const [cmd, ...args] = line.split(/\s+/); const f = ANS[cmd]; if (!f) return cprint('Method not found (code -32601)', 'err'); let a; try { a = f(args); } catch (x) { return cprint(x.message, 'err'); } if (a && a.__err) return cprint(`${a.__err.message} (code ${a.__err.code})`, 'err'); cprint(typeof a === 'string' ? a : JSON.stringify(a, null, 2)); } };
function drawTraffic() { const c = $('trc'), dpr = devicePixelRatio; c.width = c.clientWidth * dpr; c.height = 260 * dpr; const x = c.getContext('2d'); x.clearRect(0, 0, c.width, c.height); x.strokeStyle = '#ddd'; for (let i = 1; i < 5; i++) { x.beginPath(); x.moveTo(0, c.height * i / 5); x.lineTo(c.width, c.height * i / 5); x.stroke(); } x.fillStyle = '#555'; x.font = `${11 * dpr}px DejaVu Sans, sans-serif`; x.fillText(`received ${(node.recv / 1e6).toFixed(2)} MB in this session: the snapshot${node.hist.length ? ' and the block file' : ''}; a per-second graph is next`, 8 * dpr, 14 * dpr); }
// ---- go
walletInit().catch((e) => { cprint('wallet could not start: ' + e.message, 'err'); $('rcvaddr').value = 'wallet could not start: ' + e.message; });
tn.on('message', onMessage); tn.on('sync', ({ msg, pct, eta }) => setSync(msg, pct, eta)); tn.on('hist', renderHist); tn.on('log', ({ text, level }) => cprint(level === 'err' ? text : '· ' + text, level));
tn.on('seeding', () => { if (document.querySelector('#nwtabs div.on')?.dataset.t === 'peers') renderPeers(); renderInfo(); });
try { await tn.start(); } catch (e) { setSync('Error: could not start the node: ' + e.message, null); cprint('could not start the node: ' + e.message, 'err'); }
applyDisplay();
